INFO 2024-09-25 14:32:13,838 autoreload Watching for file changes with StatReloader
INFO 2024-09-25 15:02:17,109 basehttp "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2024-09-25 15:02:21,267 basehttp "POST /login/ HTTP/1.1" 200 82
INFO 2024-10-04 14:11:43,893 autoreload Watching for file changes with StatReloader
INFO 2024-10-04 14:13:09,494 autoreload Watching for file changes with StatReloader
INFO 2024-10-04 14:13:34,839 autoreload Watching for file changes with StatReloader
INFO 2024-10-04 14:14:28,889 basehttp "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2024-10-04 14:14:31,282 basehttp "POST /login/ HTTP/1.1" 200 82
INFO 2024-10-04 14:14:31,773 basehttp "OPTIONS /contacts/ HTTP/1.1" 200 0
INFO 2024-10-04 14:14:31,804 basehttp "OPTIONS /contacts/ HTTP/1.1" 200 0
INFO 2024-10-04 14:14:32,066 basehttp "OPTIONS /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 0
INFO 2024-10-04 14:14:32,161 basehttp "OPTIONS /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 0
INFO 2024-10-04 14:14:33,979 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:14:35,357 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 14:14:35,827 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:14:37,032 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 14:14:41,574 basehttp "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2024-10-04 14:14:43,030 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 14:14:58,627 basehttp "POST /login/ HTTP/1.1" 200 102
INFO 2024-10-04 14:14:59,223 basehttp "OPTIONS /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 0
INFO 2024-10-04 14:15:01,135 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 14:15:01,849 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 14:15:03,000 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 14:15:03,500 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 14:15:03,567 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 14:15:10,106 basehttp "POST /login/ HTTP/1.1" 200 82
INFO 2024-10-04 14:15:12,387 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:15:13,367 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 14:15:14,260 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:15:15,026 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 14:15:16,216 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 14:15:24,804 basehttp "POST /login/ HTTP/1.1" 200 102
INFO 2024-10-04 14:15:27,219 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 14:15:28,067 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 14:15:29,092 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 14:15:29,713 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 14:16:56,198 basehttp "POST /logout/ HTTP/1.1" 200 27
WARNING 2024-10-04 14:58:28,981 log Unauthorized: /login/
WARNING 2024-10-04 14:58:28,981 basehttp "POST /login/ HTTP/1.1" 401 29
INFO 2024-10-04 14:58:59,531 basehttp "POST /login/ HTTP/1.1" 200 82
INFO 2024-10-04 14:59:02,923 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:59:03,133 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 14:59:04,780 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 14:59:04,782 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:59:07,056 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 14:59:20,918 basehttp "POST /login/ HTTP/1.1" 200 102
INFO 2024-10-04 14:59:23,245 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 14:59:24,483 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 14:59:25,097 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 14:59:26,132 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 14:59:26,971 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 14:59:38,240 basehttp "POST /login/ HTTP/1.1" 200 82
INFO 2024-10-04 14:59:40,539 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:59:41,564 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 14:59:42,393 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:59:43,237 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 14:59:45,289 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 14:59:51,070 basehttp "POST /login/ HTTP/1.1" 200 82
INFO 2024-10-04 14:59:53,192 basehttp "GET /contacts/ HTTP/1.1" 200 94589
INFO 2024-10-04 14:59:53,283 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:59:55,196 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 14:59:55,813 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 14:59:56,200 basehttp "GET /contacts/ HTTP/1.1" 200 94589
INFO 2024-10-04 15:46:53,666 basehttp "POST /login/ HTTP/1.1" 200 102
INFO 2024-10-04 15:46:57,142 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 15:46:57,291 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 15:46:59,305 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 15:46:59,453 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 15:47:00,629 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 16:45:30,656 basehttp "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2024-10-04 16:45:35,008 basehttp "POST /login/ HTTP/1.1" 200 82
INFO 2024-10-04 16:45:37,229 basehttp "OPTIONS /contacts/ HTTP/1.1" 200 0
INFO 2024-10-04 16:45:37,259 basehttp "OPTIONS /contacts/ HTTP/1.1" 200 0
INFO 2024-10-04 16:45:38,305 basehttp "OPTIONS /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 0
INFO 2024-10-04 16:45:38,309 basehttp "OPTIONS /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 0
INFO 2024-10-04 16:45:40,136 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 16:45:40,692 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 16:45:41,971 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 16:45:42,354 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 16:45:44,217 basehttp "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2024-10-04 16:45:45,642 basehttp "POST /logout/ HTTP/1.1" 200 27
ERROR 2024-10-04 16:49:26,264 log Internal Server Error: /login/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "nurenaistore.postgres.database.azure.com" to address: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. 


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\simplecrm\Register_login.py", line 86, in post
    user = authenticate(username=username, password=password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 46, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
          ^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1393, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 323, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 299, in _cursor
    self.ensure_connection()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "E:\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not translate host name "nurenaistore.postgres.database.azure.com" to address: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. 

ERROR 2024-10-04 16:49:26,276 basehttp "POST /login/ HTTP/1.1" 500 216350
ERROR 2024-10-04 16:49:35,058 log Internal Server Error: /login/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "nurenaistore.postgres.database.azure.com" to address: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. 


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\simplecrm\Register_login.py", line 86, in post
    user = authenticate(username=username, password=password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 46, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
          ^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1393, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 323, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 299, in _cursor
    self.ensure_connection()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "E:\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not translate host name "nurenaistore.postgres.database.azure.com" to address: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. 

ERROR 2024-10-04 16:49:35,060 basehttp "POST /login/ HTTP/1.1" 500 216350
INFO 2024-10-04 19:23:51,409 autoreload Watching for file changes with StatReloader
INFO 2024-10-04 19:25:42,396 basehttp "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2024-10-04 19:25:46,183 basehttp "POST /login/ HTTP/1.1" 200 82
INFO 2024-10-04 19:25:47,186 basehttp "OPTIONS /contacts/ HTTP/1.1" 200 0
INFO 2024-10-04 19:25:47,187 basehttp "OPTIONS /contacts/ HTTP/1.1" 200 0
INFO 2024-10-04 19:25:47,454 basehttp "OPTIONS /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 0
INFO 2024-10-04 19:25:48,017 basehttp "OPTIONS /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 0
INFO 2024-10-04 19:25:49,695 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 19:25:50,594 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 19:25:51,573 basehttp "GET /whatsapp_tenant/?business_phone_id=241683569037594 HTTP/1.1" 200 5595
INFO 2024-10-04 19:25:52,256 basehttp "GET /contacts/ HTTP/1.1" 200 9983
INFO 2024-10-04 19:25:57,123 basehttp "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2024-10-04 19:25:58,541 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 19:26:06,645 basehttp "POST /login/ HTTP/1.1" 200 102
INFO 2024-10-04 19:26:07,273 basehttp "OPTIONS /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 0
INFO 2024-10-04 19:26:09,191 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 19:26:09,849 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 19:26:11,260 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 19:26:11,658 basehttp "GET /contacts/ HTTP/1.1" 200 455
INFO 2024-10-04 19:26:12,283 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-04 19:26:20,268 basehttp "POST /login/ HTTP/1.1" 200 102
INFO 2024-10-04 19:26:22,641 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 19:26:23,056 basehttp "GET /contacts/ HTTP/1.1" 200 94589
INFO 2024-10-04 19:26:24,650 basehttp "GET /whatsapp_tenant/?business_phone_id=394345743768990 HTTP/1.1" 200 4659
INFO 2024-10-04 19:26:26,153 basehttp "GET /contacts/ HTTP/1.1" 200 94589
INFO 2024-10-04 19:26:30,615 basehttp "POST /logout/ HTTP/1.1" 200 27
INFO 2024-10-05 12:21:00,590 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:22:45,215 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\middleware\common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-10-05 12:22:45,217 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026 HTTP/1.1" 500 73812
WARNING 2024-10-05 12:23:14,338 log Forbidden (CSRF cookie not set.): /topic-modelling/""WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026"/
WARNING 2024-10-05 12:23:14,340 basehttp "POST /topic-modelling/%22%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026%22/ HTTP/1.1" 403 2870
WARNING 2024-10-05 12:23:19,222 log Forbidden (CSRF cookie not set.): /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
WARNING 2024-10-05 12:23:19,223 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 403 2870
WARNING 2024-10-05 12:23:20,359 log Forbidden (CSRF cookie not set.): /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
WARNING 2024-10-05 12:23:20,360 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 403 2870
INFO 2024-10-05 12:24:29,963 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:24:31,275 autoreload Watching for file changes with StatReloader
WARNING 2024-10-05 12:24:59,812 log Forbidden (CSRF cookie not set.): /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
WARNING 2024-10-05 12:24:59,812 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 403 2870
INFO 2024-10-05 12:25:59,243 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:26:00,663 autoreload Watching for file changes with StatReloader
WARNING 2024-10-05 12:26:30,641 log Forbidden (CSRF cookie not set.): /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
WARNING 2024-10-05 12:26:30,642 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 403 2870
INFO 2024-10-05 12:29:03,758 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:29:05,530 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 12:31:13,092 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:31:14,463 autoreload Watching for file changes with StatReloader
WARNING 2024-10-05 12:31:48,091 log Forbidden (CSRF cookie not set.): /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
WARNING 2024-10-05 12:31:48,091 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 403 2870
WARNING 2024-10-05 12:33:15,947 log Bad Request: /execute-query/
WARNING 2024-10-05 12:33:15,947 basehttp "POST /execute-query/ HTTP/1.1" 400 56
ERROR 2024-10-05 12:33:28,230 log Internal Server Error: /execute-query/
ERROR 2024-10-05 12:33:28,230 basehttp "POST /execute-query/ HTTP/1.1" 500 103
INFO 2024-10-05 12:33:38,571 basehttp "POST /execute-query/ HTTP/1.1" 200 537
WARNING 2024-10-05 12:34:05,588 log Forbidden (CSRF cookie not set.): /topic-modelling/9528227181_whatsapp_1725873748.629671/
WARNING 2024-10-05 12:34:05,589 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 403 2870
WARNING 2024-10-05 12:34:06,708 log Forbidden (CSRF cookie not set.): /topic-modelling/9528227181_whatsapp_1725873748.629671/
WARNING 2024-10-05 12:34:06,710 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 403 2870
WARNING 2024-10-05 12:34:07,839 log Forbidden (CSRF cookie not set.): /topic-modelling/9528227181_whatsapp_1725873748.629671/
WARNING 2024-10-05 12:34:07,840 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 403 2870
WARNING 2024-10-05 12:34:08,503 log Forbidden (CSRF cookie not set.): /topic-modelling/9528227181_whatsapp_1725873748.629671/
WARNING 2024-10-05 12:34:08,504 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 403 2870
WARNING 2024-10-05 12:34:08,669 log Forbidden (CSRF cookie not set.): /topic-modelling/9528227181_whatsapp_1725873748.629671/
WARNING 2024-10-05 12:34:08,669 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 403 2870
INFO 2024-10-05 12:34:21,305 autoreload D:\new_nurenai\04\backend44\simplecrm\urls.py changed, reloading.
INFO 2024-10-05 12:34:22,536 autoreload Watching for file changes with StatReloader
WARNING 2024-10-05 12:34:56,950 log Forbidden (CSRF cookie not set.): /topic-modelling/9528227181_whatsapp_1725873748.629671/
WARNING 2024-10-05 12:34:56,951 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 403 2870
INFO 2024-10-05 12:35:09,095 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:35:10,344 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 12:36:27,667 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:36:29,064 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:37:04,343 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725873748.629671/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 64, in topic_modelling_view
    topics = perform_topic_modeling(conversation_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 39, in perform_topic_modeling
    conversation_text = conversation.text
                        ^^^^^^^^^^^^^^^^^
AttributeError: 'Conversation' object has no attribute 'text'
ERROR 2024-10-05 12:37:04,345 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 500 75299
INFO 2024-10-05 12:38:30,084 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:38:31,424 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:39:06,408 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725873748.629671/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 76, in topic_modelling_view
    topic_modelling_entry, created = TopicModelling.objects.update_or_create(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x0000015129143CD0>>.
ERROR 2024-10-05 12:39:06,413 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 500 145896
INFO 2024-10-05 12:39:58,450 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:39:59,809 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:40:50,438 log Internal Server Error: /topic-modelling/"9528227181_whatsapp_1725873748.629671"/
ERROR 2024-10-05 12:40:50,439 basehttp "POST /topic-modelling/%229528227181_whatsapp_1725873748.629671%22/ HTTP/1.1" 500 47
INFO 2024-10-05 12:42:53,682 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:42:54,935 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 12:43:25,126 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:43:26,295 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:43:54,011 log Internal Server Error: /topic-modelling/"9528227181_whatsapp_1725873748.629671"/
ERROR 2024-10-05 12:43:54,012 basehttp "POST /topic-modelling/%229528227181_whatsapp_1725873748.629671%22/ HTTP/1.1" 500 47
INFO 2024-10-05 12:46:42,523 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:46:43,819 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:47:14,615 log Internal Server Error: /topic-modelling/"9528227181_whatsapp_1725873748.629671"/
ERROR 2024-10-05 12:47:14,616 basehttp "POST /topic-modelling/%229528227181_whatsapp_1725873748.629671%22/ HTTP/1.1" 500 47
ERROR 2024-10-05 12:49:39,456 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725873748.629671/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 86, in topic_modelling_view
    topic_modelling_entry, created = TopicModelling.objects.update_or_create(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x000001D38A015350>>.
ERROR 2024-10-05 12:49:39,462 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 500 145815
INFO 2024-10-05 12:50:43,200 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:50:44,518 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:51:16,947 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725873748.629671/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 87, in topic_modelling_view
    topic_modelling_entry, created = TopicModelling.objects.update_or_create(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x0000020F4B614510>>.
ERROR 2024-10-05 12:51:16,953 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 500 146325
INFO 2024-10-05 12:51:50,664 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:51:51,954 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:52:20,859 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725873748.629671/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 80, in topic_modelling_view
    user = conversation.user
           ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'conversation' where it is not associated with a value
ERROR 2024-10-05 12:52:20,860 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 500 71992
INFO 2024-10-05 12:53:09,967 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:53:11,380 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:53:44,218 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725397291.565557/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 78, in topic_modelling_view
    user = conversation.user
           ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'conversation' where it is not associated with a value
ERROR 2024-10-05 12:53:44,219 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725397291.565557/ HTTP/1.1" 500 73211
INFO 2024-10-05 12:58:24,606 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 12:58:26,130 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 12:58:52,347 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 12:59:52,690 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725397291.565557/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "nurenaistore.postgres.database.azure.com" (137.116.93.194), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\simplecrm\middleware.py", line 51, in process_request
    tenant = Tenant.objects.get(id=tenant_id)  # Use the 'id' field for tenant_id
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
          ^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1393, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 323, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 299, in _cursor
    self.ensure_connection()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "E:\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: connection to server at "nurenaistore.postgres.database.azure.com" (137.116.93.194), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

ERROR 2024-10-05 12:59:52,712 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725397291.565557/ HTTP/1.1" 500 169864
ERROR 2024-10-05 13:00:16,498 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725397291.565557/
ERROR 2024-10-05 13:00:16,499 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725397291.565557/ HTTP/1.1" 500 47
INFO 2024-10-05 13:01:38,272 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 13:01:39,516 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 13:02:36,028 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725397291.565557/ HTTP/1.1" 200 3151
ERROR 2024-10-05 13:03:57,699 log Internal Server Error: /topic-modelling/"ankur Kumar <ankury639@gmail.com>_email_1725397295.262937/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "nurenaistore.postgres.database.azure.com" to address: No such host is known. 


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 87, in topic_modelling_view
    conversation = get_object_or_404(Conversation, conversation_id=conversation_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
          ^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1393, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 323, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 299, in _cursor
    self.ensure_connection()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "E:\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not translate host name "nurenaistore.postgres.database.azure.com" to address: No such host is known. 

ERROR 2024-10-05 13:03:57,705 basehttp "POST /topic-modelling/%22ankur%20Kumar%20%3Cankury639@gmail.com%3E_email_1725397295.262937/ HTTP/1.1" 500 173929
INFO 2024-10-05 13:04:37,378 basehttp "POST /topic-modelling/ankur%20Kumar%20%3Cankury639@gmail.com%3E_email_1725397295.262937/ HTTP/1.1" 200 2550
INFO 2024-10-05 13:06:14,846 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 13:06:16,106 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 13:07:32,997 basehttp "POST /topic-modelling/ankur%20Kumar%20%3Cankury639@gmail.com%3E_email_1725397295.262937/ HTTP/1.1" 200 1454
INFO 2024-10-05 13:11:18,112 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 13:11:19,724 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 13:11:56,800 basehttp "POST /topic-modelling/ankur%20Kumar%20%3Cankury639@gmail.com%3E_email_1725397295.262937/ HTTP/1.1" 200 1830
INFO 2024-10-05 13:13:00,792 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 13:13:02,005 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 13:19:39,115 autoreload D:\new_nurenai\04\backend44\communication\prompting.py changed, reloading.
INFO 2024-10-05 13:19:40,424 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 13:21:53,747 autoreload D:\new_nurenai\04\backend44\communication\prompting.py changed, reloading.
INFO 2024-10-05 13:21:54,993 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 13:22:42,783 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725346825.920227/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
topicmodelling.models.TopicModelling.DoesNotExist: TopicModelling matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 107, in topic_modelling_view
    topic_modelling_entry, created = TopicModelling.objects.update_or_create(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 930, in get_or_create
    params = self._extract_model_params(defaults, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 993, in _extract_model_params
    raise exceptions.FieldError(
django.core.exceptions.FieldError: Invalid field name(s) for model TopicModelling: 'sentiment'.
ERROR 2024-10-05 13:22:42,785 basehttp "POST /topic-modelling/9528227181_whatsapp_1725346825.920227/ HTTP/1.1" 500 110116
INFO 2024-10-05 13:25:33,386 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 13:25:34,707 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 13:26:31,508 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725346825.920227/
ERROR 2024-10-05 13:26:31,509 basehttp "POST /topic-modelling/9528227181_whatsapp_1725346825.920227/ HTTP/1.1" 500 47
INFO 2024-10-05 13:27:00,296 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 13:27:01,761 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 13:27:57,521 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 13:27:58,649 autoreload Watching for file changes with StatReloader
WARNING 2024-10-05 13:28:31,892 log Not Found: /topic-modelling/"9528227181_whatsapp_1725539516.926306"/
WARNING 2024-10-05 13:28:31,892 basehttp "POST /topic-modelling/%229528227181_whatsapp_1725539516.926306%22/ HTTP/1.1" 404 15761
ERROR 2024-10-05 13:28:58,568 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725539516.926306/
ERROR 2024-10-05 13:28:58,568 basehttp "POST /topic-modelling/9528227181_whatsapp_1725539516.926306/ HTTP/1.1" 500 47
ERROR 2024-10-05 13:30:02,533 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725539516.926306/
ERROR 2024-10-05 13:30:02,533 basehttp "POST /topic-modelling/9528227181_whatsapp_1725539516.926306/ HTTP/1.1" 500 47
INFO 2024-10-05 13:56:17,869 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 13:56:19,263 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 13:57:20,384 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725539516.926306/
ERROR 2024-10-05 13:57:20,385 basehttp "POST /topic-modelling/9528227181_whatsapp_1725539516.926306/ HTTP/1.1" 500 47
ERROR 2024-10-05 13:58:04,726 log Internal Server Error: /topic-modelling/9528227181_whatsapp_1725539516.926306/
ERROR 2024-10-05 13:58:04,727 basehttp "POST /topic-modelling/9528227181_whatsapp_1725539516.926306/ HTTP/1.1" 500 47
WARNING 2024-10-05 13:59:04,087 log Not Found: /topic-modelling/"WhatsApp Business Team"" <notification@facebookmail.com>_email_1725873734.90941/
WARNING 2024-10-05 13:59:04,087 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 404 15918
ERROR 2024-10-05 13:59:25,378 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
ERROR 2024-10-05 13:59:25,378 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 47
INFO 2024-10-05 14:01:34,259 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:01:35,208 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:02:36,083 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
topicmodelling.models.TopicModelling.DoesNotExist: TopicModelling matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 126, in topic_modelling_view
    topic_modelling_entry, created = TopicModelling.objects.update_or_create(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 930, in get_or_create
    params = self._extract_model_params(defaults, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 993, in _extract_model_params
    raise exceptions.FieldError(
django.core.exceptions.FieldError: Invalid field name(s) for model TopicModelling: 'sentiment', 'sentiment_score'.
ERROR 2024-10-05 14:02:36,085 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 115579
INFO 2024-10-05 14:09:45,611 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:09:46,619 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:10:40,608 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 131, in topic_modelling_view
    sentiment_entry, created = SentimentAnalysis.objects.update_or_create(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:10:40,612 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153985
INFO 2024-10-05 14:11:14,073 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:11:15,012 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:12:24,609 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 131, in topic_modelling_view
    communication_sentiment_entry, created = SentimentAnalysis.objects.update_or_create(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:12:24,612 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153358
INFO 2024-10-05 14:13:53,225 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:13:54,212 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:14:41,193 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 131, in topic_modelling_view
    communication_sentiment_entry, created = SentimentAnalysis.objects.update_or_create(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:14:41,197 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153255
INFO 2024-10-05 14:17:40,779 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:17:41,760 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:18:28,197 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 131, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:18:28,199 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153690
INFO 2024-10-05 14:20:14,253 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:20:15,214 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:21:02,114 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 131, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:21:02,118 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153385
INFO 2024-10-05 14:24:57,497 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:24:58,435 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:25:42,874 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 140, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:25:42,877 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153352
INFO 2024-10-05 14:29:04,990 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:29:05,987 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 14:29:34,818 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:30:24,743 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 134, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:30:24,746 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153239
INFO 2024-10-05 14:34:22,738 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:34:23,858 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:35:03,355 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 134, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:35:03,360 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153379
INFO 2024-10-05 14:36:43,049 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:36:44,394 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:37:22,198 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 118, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:37:22,201 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153093
ERROR 2024-10-05 14:37:40,753 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 118, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:37:40,755 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153582
INFO 2024-10-05 14:37:51,009 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:38:35,298 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 118, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '"WhatsApp Business Team" <notification@facebookmail.com>_email_1725873734.90941'.
ERROR 2024-10-05 14:38:35,301 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725873734.90941/ HTTP/1.1" 500 153523
ERROR 2024-10-05 14:39:24,710 log Internal Server Error: /topic-modelling/9456023345_whatsapp_1725873736.65468/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '9456023345_whatsapp_1725873736.65468'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 118, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '9456023345_whatsapp_1725873736.65468'.
ERROR 2024-10-05 14:39:24,711 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 500 148018
INFO 2024-10-05 14:42:23,073 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:42:24,279 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:43:12,620 log Internal Server Error: /topic-modelling/9456023345_whatsapp_1725873736.65468/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '9456023345_whatsapp_1725873736.65468'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 121, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '9456023345_whatsapp_1725873736.65468'.
ERROR 2024-10-05 14:43:12,635 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 500 148050
ERROR 2024-10-05 14:43:34,474 log Internal Server Error: /topic-modelling/9456023345_whatsapp_1725873736.65468/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '9456023345_whatsapp_1725873736.65468'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 121, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '9456023345_whatsapp_1725873736.65468'.
ERROR 2024-10-05 14:43:34,477 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 500 147810
INFO 2024-10-05 14:43:54,807 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:43:56,251 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:44:48,996 log Internal Server Error: /topic-modelling/9456023345_whatsapp_1725873736.65468/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '9456023345_whatsapp_1725873736.65468'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 134, in topic_modelling_view
    communication_sentimentanalysis_entry, created = SentimentAnalysis.objects.update_or_create(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'message_id' expected a number but got '9456023345_whatsapp_1725873736.65468'.
ERROR 2024-10-05 14:44:49,001 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 500 148121
INFO 2024-10-05 14:46:07,787 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:46:09,725 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:46:49,478 log Internal Server Error: /topic-modelling/9456023345_whatsapp_1725873736.65468/
Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
topicmodelling.models.TopicModelling.DoesNotExist: TopicModelling matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "contact_id_id" violates not-null constraint
DETAIL:  Failing row contains (154, ["NMF method can't be effectively used for these messages as the..., 111, 3, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\new_nurenai\04\backend44\topicmodelling\views.py", line 80, in topic_modelling_view
    topicmodelling_topicmodelling_entry, created = TopicModelling.objects.update_or_create(
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 961, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 935, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "E:\.venv\Lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "E:\.venv\Lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "E:\.venv\Lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "E:\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "contact_id_id" violates not-null constraint
DETAIL:  Failing row contains (154, ["NMF method can't be effectively used for these messages as the..., 111, 3, null).

ERROR 2024-10-05 14:46:49,483 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 500 176807
INFO 2024-10-05 14:48:55,288 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:48:56,882 autoreload Watching for file changes with StatReloader
WARNING 2024-10-05 14:49:34,666 log Bad Request: /topic-modelling/9456023345_whatsapp_1725873736.65468/
WARNING 2024-10-05 14:49:34,666 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 400 221
INFO 2024-10-05 14:51:32,157 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 14:51:33,411 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:52:04,104 log Internal Server Error: /topic-modelling/9456023345_whatsapp_1725873736.65468/
ERROR 2024-10-05 14:52:04,105 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 500 82
INFO 2024-10-05 14:54:44,979 autoreload D:\new_nurenai\04\backend44\communication\models.py changed, reloading.
INFO 2024-10-05 14:54:46,499 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:55:15,597 log Internal Server Error: /topic-modelling/9456023345_whatsapp_1725873736.65468/
ERROR 2024-10-05 14:55:15,598 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 500 148
INFO 2024-10-05 14:57:53,772 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 14:59:08,056 log Internal Server Error: /topic-modelling/9456023345_whatsapp_1725873736.65468/
ERROR 2024-10-05 14:59:08,057 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 500 148
INFO 2024-10-05 15:00:31,447 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 15:00:59,464 log Internal Server Error: /topic-modelling/9456023345_whatsapp_1725873736.65468/
ERROR 2024-10-05 15:00:59,465 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 500 148
INFO 2024-10-05 15:02:39,775 autoreload D:\new_nurenai\04\backend44\topicmodelling\models.py changed, reloading.
INFO 2024-10-05 15:02:41,040 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 15:04:45,123 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 15:05:33,595 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 200 746
INFO 2024-10-05 15:10:45,387 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:10:46,970 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 15:11:29,134 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 200 362
INFO 2024-10-05 15:12:39,559 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:12:40,941 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 15:13:14,303 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 200 123
INFO 2024-10-05 15:13:53,011 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 200 655
INFO 2024-10-05 15:15:09,282 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:15:10,844 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 15:15:52,427 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
ERROR 2024-10-05 15:15:52,429 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 500 47
ERROR 2024-10-05 15:16:23,751 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
ERROR 2024-10-05 15:16:23,753 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 500 47
INFO 2024-10-05 15:27:59,430 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:28:00,877 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 15:28:40,834 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
ERROR 2024-10-05 15:28:40,834 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 500 47
INFO 2024-10-05 15:30:46,579 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 15:31:26,426 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
ERROR 2024-10-05 15:31:26,426 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 500 47
INFO 2024-10-05 15:32:26,658 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:32:27,974 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 15:33:11,077 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
ERROR 2024-10-05 15:33:11,077 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 500 47
INFO 2024-10-05 15:35:35,271 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:35:36,543 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 15:36:37,266 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
ERROR 2024-10-05 15:36:37,266 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 500 47
INFO 2024-10-05 15:43:57,649 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:43:59,015 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 15:44:34,047 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
ERROR 2024-10-05 15:44:34,048 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 500 47
INFO 2024-10-05 15:46:03,760 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:46:05,131 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 15:47:49,159 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
ERROR 2024-10-05 15:47:49,159 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 500 47
INFO 2024-10-05 15:48:47,371 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:48:48,716 autoreload Watching for file changes with StatReloader
ERROR 2024-10-05 15:49:25,412 log Internal Server Error: /topic-modelling/"WhatsApp Business Team" <notification@facebookmail.com>_email_1725539502.356026/
ERROR 2024-10-05 15:49:25,413 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 500 47
INFO 2024-10-05 15:49:48,746 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:49:50,037 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 15:50:46,626 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 15:50:47,972 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 15:51:54,602 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 200 877
INFO 2024-10-05 15:57:27,686 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 200 1142
INFO 2024-10-05 15:58:13,178 basehttp "POST /topic-modelling/919536330961_whatsapp_1725873750.57828/ HTTP/1.1" 200 404
INFO 2024-10-05 15:59:18,626 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 200 1213
INFO 2024-10-05 16:01:57,747 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 200 888
INFO 2024-10-05 16:29:25,362 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-05 16:29:26,381 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 16:43:08,002 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-05 16:43:09,355 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 16:49:56,936 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-05 16:49:58,371 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 17:10:58,382 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-05 17:11:00,320 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 17:13:34,338 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-05 17:13:35,779 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 17:13:59,986 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-05 17:14:01,185 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 17:29:45,831 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-05 17:29:47,299 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 22:13:05,611 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 22:13:06,966 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 22:13:39,748 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 200 476
INFO 2024-10-05 22:15:41,883 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 22:15:43,130 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 22:16:44,073 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 200 135
INFO 2024-10-05 22:17:28,984 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 22:17:30,305 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 22:18:28,420 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 200 157
INFO 2024-10-05 22:19:01,496 basehttp "POST /topic-modelling/9456023345_whatsapp_1725539503.936241/ HTTP/1.1" 200 86
INFO 2024-10-05 22:19:16,931 basehttp "POST /topic-modelling/3789012_whatsapp_1725539507.724368/ HTTP/1.1" 200 326
INFO 2024-10-05 22:20:58,388 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 22:20:59,817 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 22:35:17,311 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 22:35:18,416 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 22:35:47,107 basehttp "POST /topic-modelling/3789012_whatsapp_1725539507.724368/ HTTP/1.1" 200 158
INFO 2024-10-05 22:38:11,334 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 22:38:12,327 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 22:38:45,251 basehttp "POST /topic-modelling/3789012_whatsapp_1725539507.724368/ HTTP/1.1" 200 77
ERROR 2024-10-05 22:39:00,003 log Internal Server Error: /topic-modelling/"9528227181_whatsapp_1725873748.629671"/
ERROR 2024-10-05 22:39:00,004 basehttp "POST /topic-modelling/%229528227181_whatsapp_1725873748.629671%22/ HTTP/1.1" 500 71
INFO 2024-10-05 22:39:20,935 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 200 77
INFO 2024-10-05 22:42:01,694 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 22:42:02,681 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 22:42:53,394 basehttp "POST /topic-modelling/9528227181_whatsapp_1725873748.629671/ HTTP/1.1" 200 77
INFO 2024-10-05 23:12:39,913 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 200 77
INFO 2024-10-05 23:13:05,121 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 23:13:06,133 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 23:13:49,225 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 200 77
INFO 2024-10-05 23:14:32,172 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 23:14:33,185 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 23:15:10,952 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 200 208
INFO 2024-10-05 23:17:26,889 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-05 23:17:27,837 autoreload Watching for file changes with StatReloader
INFO 2024-10-05 23:18:12,711 basehttp "POST /topic-modelling/9456023345_whatsapp_1725873736.65468/ HTTP/1.1" 200 78
INFO 2024-10-05 23:19:38,716 basehttp "POST /topic-modelling/3789012_whatsapp_1725539507.724368/ HTTP/1.1" 200 310
INFO 2024-10-06 14:33:45,486 autoreload Watching for file changes with StatReloader
WARNING 2024-10-06 14:45:29,543 log Bad Request: /save_whatsapp_conversations/
WARNING 2024-10-06 14:45:29,544 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 400 54
WARNING 2024-10-06 15:02:24,947 log Bad Request: /save_whatsapp_conversations/
WARNING 2024-10-06 15:02:24,947 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 400 54
INFO 2024-10-06 15:02:33,902 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 15:02:34,867 autoreload Watching for file changes with StatReloader
WARNING 2024-10-06 15:37:10,607 log Bad Request: /save_whatsapp_conversations/
WARNING 2024-10-06 15:37:10,608 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 400 54
WARNING 2024-10-06 15:48:47,967 log Bad Request: /save_whatsapp_conversations/
WARNING 2024-10-06 15:48:47,968 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 400 54
WARNING 2024-10-06 16:02:54,557 log Bad Request: /save_whatsapp_conversations/
WARNING 2024-10-06 16:02:54,558 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 400 54
WARNING 2024-10-06 16:15:52,913 log Bad Request: /save_whatsapp_conversations/
WARNING 2024-10-06 16:15:52,914 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 400 54
WARNING 2024-10-06 16:28:54,246 log Bad Request: /save_whatsapp_conversations/
WARNING 2024-10-06 16:28:54,247 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 400 54
WARNING 2024-10-06 16:43:28,265 log Bad Request: /save_whatsapp_conversations/
WARNING 2024-10-06 16:43:28,267 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 400 54
INFO 2024-10-06 17:24:53,320 autoreload D:\new_nurenai\04\backend44\interaction\views.py changed, reloading.
INFO 2024-10-06 17:24:54,758 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 20:16:23,077 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 20:17:24,956 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 20:19:49,640 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 20:22:24,376 autoreload D:\new_nurenai\04\backend44\interaction\models.py changed, reloading.
INFO 2024-10-06 20:22:25,577 autoreload Watching for file changes with StatReloader
WARNING 2024-10-06 20:25:50,970 log Not Found: /group-message/
WARNING 2024-10-06 20:25:50,970 basehttp "POST /group-message/ HTTP/1.1" 404 21804
ERROR 2024-10-06 20:26:05,287 log Internal Server Error: /group-messages/
ERROR 2024-10-06 20:26:05,288 basehttp "POST /group-messages/ HTTP/1.1" 500 311
INFO 2024-10-06 20:31:47,797 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 20:31:49,074 autoreload Watching for file changes with StatReloader
ERROR 2024-10-06 20:32:44,660 log Internal Server Error: /group-messages/
ERROR 2024-10-06 20:32:44,661 basehttp "POST /group-messages/ HTTP/1.1" 500 105
INFO 2024-10-06 22:17:12,846 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 22:17:14,090 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 22:17:45,044 autoreload Watching for file changes with StatReloader
ERROR 2024-10-06 22:19:40,546 log Internal Server Error: /group-messages/
ERROR 2024-10-06 22:19:40,547 basehttp "POST /group-messages/ HTTP/1.1" 500 66
INFO 2024-10-06 22:23:26,492 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 22:23:27,796 autoreload Watching for file changes with StatReloader
ERROR 2024-10-06 22:23:52,973 log Internal Server Error: /group-messages/
ERROR 2024-10-06 22:23:52,974 basehttp "POST /group-messages/ HTTP/1.1" 500 97
INFO 2024-10-06 22:25:23,990 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 22:25:25,337 autoreload Watching for file changes with StatReloader
ERROR 2024-10-06 22:25:56,880 log Internal Server Error: /group-messages/
ERROR 2024-10-06 22:25:56,880 basehttp "POST /group-messages/ HTTP/1.1" 500 90
INFO 2024-10-06 22:28:32,843 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-06 22:28:34,189 autoreload Watching for file changes with StatReloader
ERROR 2024-10-06 22:29:04,584 log Internal Server Error: /group-messages/
ERROR 2024-10-06 22:29:04,585 basehttp "POST /group-messages/ HTTP/1.1" 500 122
INFO 2024-10-06 22:34:20,139 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-06 22:34:21,605 autoreload Watching for file changes with StatReloader
ERROR 2024-10-06 22:34:57,753 log Internal Server Error: /group-messages/
ERROR 2024-10-06 22:34:57,753 basehttp "POST /group-messages/ HTTP/1.1" 500 122
ERROR 2024-10-06 22:35:04,525 log Internal Server Error: /group-messages/
ERROR 2024-10-06 22:35:04,525 basehttp "POST /group-messages/ HTTP/1.1" 500 122
INFO 2024-10-06 22:36:50,115 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-06 22:36:51,496 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 22:37:11,969 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 22:37:13,226 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 22:41:52,848 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 22:41:54,277 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 22:50:52,835 autoreload D:\new_nurenai\04\backend44\interaction\views.py changed, reloading.
INFO 2024-10-06 22:50:54,292 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 22:51:20,868 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 22:51:21,861 autoreload Watching for file changes with StatReloader
WARNING 2024-10-06 22:53:21,273 log Not Found: /save_whatsapp_conversations/
WARNING 2024-10-06 22:53:21,274 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 404 21840
INFO 2024-10-06 22:54:09,502 autoreload D:\new_nurenai\04\backend44\simplecrm\urls.py changed, reloading.
INFO 2024-10-06 22:54:10,671 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 23:07:04,670 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 23:07:06,088 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 23:11:44,764 autoreload D:\new_nurenai\04\backend44\communication\views.py changed, reloading.
INFO 2024-10-06 23:11:45,945 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 23:12:47,955 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-06 23:12:49,330 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 23:16:16,232 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 23:18:11,611 autoreload D:\new_nurenai\04\backend44\interaction\views.py changed, reloading.
INFO 2024-10-06 23:18:12,798 autoreload Watching for file changes with StatReloader
INFO 2024-10-06 23:21:01,970 autoreload Watching for file changes with StatReloader
WARNING 2024-10-06 23:22:07,680 log Bad Request: /save_whatsapp_conversations/
WARNING 2024-10-06 23:22:07,681 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 400 54
INFO 2024-10-06 23:25:14,576 autoreload D:\new_nurenai\04\backend44\interaction\views.py changed, reloading.
INFO 2024-10-06 23:25:15,602 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 00:34:00,559 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 201 68
INFO 2024-10-07 00:35:38,301 autoreload D:\new_nurenai\04\backend44\interaction\views.py changed, reloading.
INFO 2024-10-07 00:35:39,965 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 00:36:12,606 basehttp "POST /save_whatsapp_conversations/ HTTP/1.1" 201 68
ERROR 2024-10-07 00:36:38,014 log Internal Server Error: /group-messages/
ERROR 2024-10-07 00:36:38,015 basehttp "POST /group-messages/ HTTP/1.1" 500 66
INFO 2024-10-07 00:44:13,165 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 00:52:33,923 autoreload Watching for file changes with StatReloader
ERROR 2024-10-07 00:55:32,920 log Internal Server Error: /group-messages/
ERROR 2024-10-07 00:55:32,921 basehttp "POST /group-messages/ HTTP/1.1" 500 66
INFO 2024-10-07 00:55:48,203 autoreload Watching for file changes with StatReloader
ERROR 2024-10-07 01:00:57,700 log Internal Server Error: /group-messages/
ERROR 2024-10-07 01:00:57,700 basehttp "POST /group-messages/ HTTP/1.1" 500 66
ERROR 2024-10-07 01:01:34,877 log Internal Server Error: /group-messages/
ERROR 2024-10-07 01:01:34,878 basehttp "POST /group-messages/ HTTP/1.1" 500 66
INFO 2024-10-07 01:12:11,552 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:15:15,918 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-07 01:15:16,899 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:19:14,698 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:22:09,362 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:24:26,815 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-07 01:24:27,918 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:32:22,155 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:36:12,658 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:37:43,067 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:41:07,479 autoreload D:\new_nurenai\04\backend44\communication\insta_msg.py changed, reloading.
INFO 2024-10-07 01:41:08,840 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:51:29,500 basehttp "POST /group-messages/ HTTP/1.1" 200 63
INFO 2024-10-07 01:53:56,120 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 01:55:27,567 basehttp "POST /group-messages/ HTTP/1.1" 200 63
INFO 2024-10-07 01:56:09,040 basehttp "POST /group-messages/ HTTP/1.1" 200 63
WARNING 2024-10-07 02:54:52,355 log Bad Request: /topic-modelling/9528227181_whatsapp_1725539516.926306/
WARNING 2024-10-07 02:54:52,356 basehttp "GET /topic-modelling/9528227181_whatsapp_1725539516.926306/ HTTP/1.1" 400 21
WARNING 2024-10-07 02:55:01,320 log Bad Request: /topic-modelling/9528227181_whatsapp_1725539516.926306/
WARNING 2024-10-07 02:55:01,321 basehttp "GET /topic-modelling/9528227181_whatsapp_1725539516.926306/ HTTP/1.1" 400 36
INFO 2024-10-07 02:55:10,109 basehttp "POST /topic-modelling/9528227181_whatsapp_1725539516.926306/ HTTP/1.1" 200 77
INFO 2024-10-07 02:55:48,745 basehttp "POST /topic-modelling/919548265904_whatsapp_1728242104.70971/ HTTP/1.1" 200 441
ERROR 2024-10-07 03:00:13,922 log Internal Server Error: /topic-modelling/919548265904_whatsapp_1728242105.378814/
ERROR 2024-10-07 03:00:13,923 basehttp "POST /topic-modelling/919548265904_whatsapp_1728242105.378814/ HTTP/1.1" 500 47
ERROR 2024-10-07 03:11:00,984 log Internal Server Error: /topic-modelling/919548265904_whatsapp_1728242577.15486/
ERROR 2024-10-07 03:11:00,985 basehttp "POST /topic-modelling/919548265904_whatsapp_1728242577.15486/ HTTP/1.1" 500 47
ERROR 2024-10-07 03:17:12,458 log Internal Server Error: /topic-modelling/919643393874_whatsapp_1728243715.259426/
ERROR 2024-10-07 03:17:12,458 basehttp "POST /topic-modelling/919643393874_whatsapp_1728243715.259426/ HTTP/1.1" 500 47
INFO 2024-10-07 03:27:43,848 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-07 03:27:45,870 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 03:29:03,215 basehttp "POST /topic-modelling/919643393874_whatsapp_1728243715.259426/ HTTP/1.1" 200 330
INFO 2024-10-07 03:30:36,804 basehttp "POST /topic-modelling/919536330961_whatsapp_1728246353.372116/ HTTP/1.1" 200 299
INFO 2024-10-07 03:32:26,810 basehttp "POST /topic-modelling/919868789610_whatsapp_1728246314.165662/ HTTP/1.1" 200 275
INFO 2024-10-07 09:44:55,618 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 10:22:11,741 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 10:23:23,211 basehttp "POST /topic-modelling/919899009092_whatsapp_1728246281.893791/ HTTP/1.1" 200 798
INFO 2024-10-07 10:25:39,381 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-07 10:25:40,862 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 10:26:18,285 basehttp "POST /topic-modelling/919899009092_whatsapp_1728246281.893791/ HTTP/1.1" 200 914
INFO 2024-10-07 10:59:47,848 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-07 10:59:49,164 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 11:00:13,723 autoreload D:\new_nurenai\04\backend44\topicmodelling\views.py changed, reloading.
INFO 2024-10-07 11:00:14,924 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 11:01:05,951 basehttp "POST /topic-modelling/919899009092_whatsapp_1728246281.893791/ HTTP/1.1" 200 609
INFO 2024-10-07 11:05:30,648 basehttp "POST /topic-modelling/919899009092_whatsapp_1728246281.893791/ HTTP/1.1" 200 387
INFO 2024-10-07 11:08:17,670 basehttp "POST /topic-modelling/9456023345_whatsapp_1725346815.591252/ HTTP/1.1" 200 81
INFO 2024-10-07 11:08:54,223 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725397291.565557/ HTTP/1.1" 200 299
INFO 2024-10-07 11:09:19,883 basehttp "POST /topic-modelling/%22Facebook%22%20%3Cnotification@facebookmail.com%3E_email_1725397294.178328/ HTTP/1.1" 200 186
INFO 2024-10-07 11:09:37,643 basehttp "POST /topic-modelling/ankur%20Kumar%20%3Cankury639@gmail.com%3E_email_1725397295.262937/ HTTP/1.1" 200 241
INFO 2024-10-07 11:09:59,763 basehttp "POST /topic-modelling/ankur%20Kumar%20%3Cankury639@gmail.com%3E_email_1725397295.262937/ HTTP/1.1" 200 230
INFO 2024-10-07 11:10:17,886 basehttp "POST /topic-modelling/Adarsh%20Sharma%20%3Cadarsh1885@gmail.com%3E_email_1725397297.439233/ HTTP/1.1" 200 144
INFO 2024-10-07 11:10:27,054 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539501.432752/ HTTP/1.1" 200 138
INFO 2024-10-07 11:10:50,478 basehttp "POST /topic-modelling/%22WhatsApp%20Business%20Team%22%20%3Cnotification@facebookmail.com%3E_email_1725539502.356026/ HTTP/1.1" 200 239
INFO 2024-10-07 11:19:02,358 basehttp "POST /topic-modelling/919899009092_whatsapp_1728246359.313022/ HTTP/1.1" 200 138
INFO 2024-10-07 11:39:59,085 basehttp "POST /topic-modelling/919643393874_whatsapp_1728246275.781166/ HTTP/1.1" 200 160
INFO 2024-10-07 11:44:58,616 basehttp "POST /topic-modelling/919899009092_whatsapp_1728245959.123027/ HTTP/1.1" 200 384
INFO 2024-10-07 12:12:43,459 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 12:15:34,545 basehttp "POST /topic-modelling/919868789610_whatsapp_1728246314.165662/ HTTP/1.1" 200 275
INFO 2024-10-07 12:38:37,865 autoreload Watching for file changes with StatReloader
INFO 2024-10-07 12:39:25,286 basehttp "POST /topic-modelling/919868789610_whatsapp_1728246314.165662/ HTTP/1.1" 200 419
INFO 2024-10-07 13:36:47,132 autoreload Watching for file changes with StatReloader
